[package]
name = "sockkit"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
crossbeam = "0.8.4"
dashmap = "6.1.0"
flume = "0.11.1"
tokio = {version = "1.44.1", features = ["full"]  }
uflow = "0.7.1"
